import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import MainContext from "@/context/MainContext";
import { Toaster } from "react-hot-toast";

const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${nunito.variable} light`}>
      <body>
        <MainContext>
          <Providers>{children}</Providers>
          <Toaster />
        </MainContext>
      </body>
    </html>
  );
}
