export interface Course {
  id: number;
  slug: string;
  title: string;
  subtitle: string;
  university?: string;
  location: string;
  duration: string;
  mode: string;
  intake: string;
  tuitionFee: string;
  tuitionFeeInternational?: string;
  rating: number;
  reviews: number;
  students: number;
  image: string;
  description: string;
  highlights: string[];
  modules: {
    name: string;
    credits?: number;
    duration?: string;
  }[];
  requirements: string[];
  careerOutcomes?: string[];
  category: string;
}

export const courses: Course[] = [
  {
    id: 1,
    slug: "skills-for-workplace",
    title: "Skills for Workplace",
    subtitle: "Certificate of Higher Education in Business",
    university: "University of Wales Trinity and Saint David",
    location: "Carmarthen, Wales",
    duration: "1 Year Full-time",
    mode: "Full-time",
    intake: "September 2024",
    tuitionFee: "£9,535 per year",
    rating: 4.6,
    reviews: 89,
    students: 1324,
    image: "https://images.unsplash.com/photo-1573164574572-cb89e39749b4?fm=jpg&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YnVzaW5lc3MlMjB0cmFpbmluZ3xlbnwwfHwwfHx8MA%3D%3D&ixlib=rb-4.1.0&q=60&w=3000",
    category: "Business",
    description:
      "This course provides a broad overview of business, covering areas such as finance, human resources, marketing, and management. It emphasizes problem-solving, decision-making, leadership, and communication skills, preparing you to work effectively in teams or independently. The programme combines practical work experience with academic learning, helping you apply knowledge in real-world settings and enhancing employability. You’ll also gain insights into business culture, enterprise, entrepreneurship, and digital skills. As a CertHE, it serves as a strong foundation for further study or a career in business, equipping you with transferable skills for a variety of roles.",
    highlights: [
      "Practical work experience integrated",
      "Develops leadership & communication",
      "Pathway to full bachelor’s degree",
      "Focus on digital and employability skills",
      "Ideal for career changers or returners",
      "Support for international & mature students",
    ],
    modules: [
      { name: "Academic Skills", credits: 20, duration: "12 weeks" },
      { name: "Effective Teamworking and Communication", credits: 20, duration: "12 weeks" },
      { name: "Digital Skills", credits: 20, duration: "12 weeks" },
      { name: "Problem Solving and Decision Making", credits: 20, duration: "12 weeks" },
      { name: "Employability and Career Development", credits: 20, duration: "12 weeks" },
      { name: "Enterprise and Entrepreneurship", credits: 20, duration: "12 weeks" },
    ],
    requirements: [
      "Open to A-Levels, IB, Foundation programmes",
      "IELTS 6.0 (minimum 5.5 per component)",
      "Suitable for career returners or new learners",
      "Contextual admissions available",
      "Student visa required for international students",
      "US Federal Aid: in-person study only",
    ],
    careerOutcomes: [
      "Human Resources",
      "Marketing and Sales",
      "Financial Services",
      "Public, private or third sector management",
      "Business Consultancy",
      "Postgraduate study/research",
    ],
  },
  {
    id: 2,
    slug: "fda-business-management",
    title: "FDA Business Management",
    subtitle: "Foundation Degree in Business Management",
    university: "New College Durham",
    location: "Durham, UK",
    duration: "2 Years Full-time",
    mode: "Full-time",
    intake: "September 2024",
    tuitionFee: "£9,000 per year",
    rating: 4.5,
    reviews: 76,
    students: 942,
    image: "/business-management.jpg",
    category: "Business",
    description:
      "This programme is regularly updated to keep pace with the evolving business and management landscape, helping you take the first step on the management career ladder. Our lecturers bring real-world industry experience and a wide network of professional contacts to enrich your learning and strengthen your commercial awareness.",
    highlights: [
      "Industry-experienced lecturers",
      "Strong employer links",
      "Hands-on learning approach",
      "Pathway to full bachelor's degree",
      "Focus on leadership and enterprise",
      "Work-related learning modules",
    ],
    modules: [
      { name: "Personal Professional Development 1", duration: "Year 1" },
      { name: "Innovation and Enterprise", duration: "Year 1" },
      { name: "Human Resource Management", duration: "Year 1" },
      { name: "Business Environment", duration: "Year 1" },
      { name: "Principles of Marketing", duration: "Year 1" },
      { name: "Leadership and Management", duration: "Year 1" },
      { name: "Business Event Management", duration: "Year 1" },
      { name: "Personal Professional Development 2", duration: "Year 2" },
      { name: "Work Related Learning", duration: "Year 2" },
      { name: "Entrepreneurship", duration: "Year 2" },
      { name: "Business Finance", duration: "Year 2" },
      { name: "Logistics and Supply Chain Management", duration: "Year 2" },
      { name: "Developing Collaborative Relationships", duration: "Year 2" },
      { name: "Principles of International Business", duration: "Year 2" },
    ],
    requirements: [
      "Three GCSEs grade C/4 or above (including Maths and English)",
      "Minimum 32 UCAS Tariff Points",
      "Level 3 Business qualification or Access to HE",
      "IELTS 5.5 overall",
      "Non-standard applicants welcome with relevant experience",
      "Interview and personal statement required",
    ],
    careerOutcomes: [
      "Business Analyst",
      "Team Leader",
      "Operations Manager",
      "Entrepreneur",
      "HR Assistant",
      "Sales Executive",
    ],
  },
  {
    id: 3,
    slug: "mba-marketing",
    title: "Master of Business Administration (Marketing)",
    subtitle: "MBA with Specialisation in Marketing",
    university: "UK Partner University",
    location: "London, UK",
    duration: "16-24 Months",
    mode: "Full-time / Part-time",
    intake: "January, May, September 2024",
    tuitionFee: "£10,995 (Home/EU)",
    tuitionFeeInternational: "£17,500",
    rating: 4.8,
    reviews: 134,
    students: 2105,
    image: "https://images.unsplash.com/photo-1444653614773-995cb1ef9efa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
    category: "Business",
    description:
      "This MBA with a specialisation in Marketing is designed for professionals aiming to lead in dynamic marketing environments. The programme blends strategic management with advanced marketing concepts, equipping graduates with skills to drive brand growth and innovation in global markets.",
    highlights: [
      "Specialised in Marketing strategy",
      "Globally recognised MBA qualification",
      "Taught by industry experts",
      "Flexible start dates (Jan/May/Sep)",
      "Internationally recognised degree",
      "Part-time study options available",
    ],
    modules: [
      { name: "Strategic Management", credits: 20 },
      { name: "Digital Marketing", credits: 20 },
      { name: "Consumer Behaviour", credits: 15 },
      { name: "Brand Management", credits: 15 },
      { name: "Global Marketing Strategy", credits: 20 },
      { name: "Marketing Analytics", credits: 15 },
      { name: "MBA Dissertation (Marketing)", credits: 60 },
    ],
    requirements: [
      "Minimum 2:2 UK Bachelor's degree or equivalent",
      "IELTS 6.5 (no component below 5.5)",
      "Applicants with IELTS 5.5–6.0 may take Pre-Sessional English",
      "Relevant work experience considered for non-standard applicants",
      "Pre-Master's available for qualification bridging",
    ],
    careerOutcomes: [
      "Marketing Manager",
      "Brand Director",
      "Digital Marketing Strategist",
      "Product Manager",
      "Market Research Analyst",
      "Advertising Executive",
    ],
  },
  {
    id: 4,
    slug: "mba-finance",
    title: "Master of Business Administration (Finance)",
    subtitle: "MBA with Specialisation in Finance",
    university: "UK Partner University",
    location: "London, UK",
    duration: "16-24 Months",
    mode: "Full-time / Part-time",
    intake: "January, May, September 2024",
    tuitionFee: "£10,995 (Home/EU)",
    tuitionFeeInternational: "£17,500",
    rating: 4.8,
    reviews: 128,
    students: 1973,
    image: "https://images.unsplash.com/photo-1591696205602-2f950c417cb9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
    category: "Business",
    description:
      "This MBA in Finance is tailored for aspiring financial leaders. It covers advanced financial management, investment analysis, and corporate strategy, preparing graduates for senior roles in banking, investment, and corporate finance sectors.",
    highlights: [
      "Specialisation in Financial Strategy",
      "CFA-relevant curriculum",
      "Real-world case studies",
      "Flexible learning options",
      "Global accreditation",
      "Strong industry connections",
    ],
    modules: [
      { name: "Corporate Finance", credits: 20 },
      { name: "Investment Analysis", credits: 20 },
      { name: "Risk Management", credits: 15 },
      { name: "Financial Reporting", credits: 15 },
      { name: "International Finance", credits: 20 },
      { name: "Mergers & Acquisitions", credits: 15 },
      { name: "MBA Dissertation (Finance)", credits: 60 },
    ],
    requirements: [
      "Minimum 2:2 UK Bachelor's degree or equivalent",
      "IELTS 6.5 (no component below 5.5)",
      "Applicants with IELTS 5.5–6.0 may take Pre-Sessional English",
      "Relevant work experience considered for non-standard applicants",
      "Pre-Master's available for qualification bridging",
    ],
    careerOutcomes: [
      "Financial Analyst",
      "Investment Banker",
      "Corporate Finance Manager",
      "Risk Consultant",
      "Portfolio Manager",
      "Chief Financial Officer (CFO)",
    ],
  },
  {
    id: 5,
    slug: "mba-general",
    title: "Master of Business Administration (MBA)",
    subtitle: "General MBA - Leadership & Management",
    university: "UK Partner University",
    location: "London, UK",
    duration: "16-24 Months",
    mode: "Full-time / Part-time",
    intake: "January, May, September 2024",
    tuitionFee: "£10,995 (Home/EU)",
    tuitionFeeInternational: "£17,500",
    rating: 4.9,
    reviews: 203,
    students: 3560,
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
    category: "Business",
    description:
      "Our general MBA programme is designed to develop versatile business leaders. It covers core areas such as leadership, strategy, finance, marketing, and operations, providing a holistic understanding of modern business challenges.",
    highlights: [
      "Comprehensive leadership training",
      "Global business perspective",
      "Executive networking events",
      "Flexible study modes",
      "Dissertation or consulting project",
      "Alumni career support",
    ],
    modules: [
      { name: "Leadership & Organisational Behaviour", credits: 20 },
      { name: "Strategic Management", credits: 20 },
      { name: "Financial Decision Making", credits: 15 },
      { name: "Marketing Strategy", credits: 15 },
      { name: "Operations & Supply Chain", credits: 15 },
      { name: "Business Ethics & Sustainability", credits: 15 },
      { name: "MBA Capstone Project", credits: 60 },
    ],
    requirements: [
      "Minimum 2:2 UK Bachelor's degree or equivalent",
      "IELTS 6.5 (no component below 5.5)",
      "Applicants with IELTS 5.5–6.0 may take Pre-Sessional English",
      "Relevant work experience considered for non-standard applicants",
      "Pre-Master's available for qualification bridging",
    ],
    careerOutcomes: [
      "General Manager",
      "Operations Director",
      "Business Consultant",
      "Entrepreneur",
      "Project Manager",
      "Senior Executive",
    ],
  },
  {
    id: 6,
    slug: "bsc-business-entrepreneurship",
    title: "BSc Business Management and Entrepreneurship",
    subtitle: "Undergraduate Degree in Business & Innovation",
    university: "UK Partner University",
    location: "London/Birmingham, UK",
    duration: "3 Years",
    mode: "Full-time",
    intake: "January, May, September 2024",
    tuitionFee: "Approx. £9,500 per year (Home)",
    tuitionFeeInternational: "£8,000 – £18,500 per year",
    rating: 4.5,
    reviews: 95,
    students: 1678,
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
    category: "Business",
    description:
      "This degree combines core business principles with a strong focus on innovation and entrepreneurship. You’ll learn how to launch and manage startups, develop business plans, and think creatively about solving real-world problems.",
    highlights: [
      "Entrepreneurship-focused curriculum",
      "Startup incubator access",
      "Pitch competitions and mentorship",
      "Real business projects",
      "Flexible start dates",
      "Internationally recognised degree",
    ],
    modules: [
      { name: "Introduction to Business", duration: "Year 1" },
      { name: "Principles of Marketing", duration: "Year 1" },
      { name: "Financial Literacy", duration: "Year 1" },
      { name: "Entrepreneurial Mindset", duration: "Year 1" },
      { name: "Business Planning", duration: "Year 2" },
      { name: "Innovation Management", duration: "Year 2" },
      { name: "Digital Business", duration: "Year 2" },
      { name: "Startup Project", duration: "Year 3" },
      { name: "Scaling Ventures", duration: "Year 3" },
      { name: "Sustainable Entrepreneurship", duration: "Year 3" },
    ],
    requirements: [
      "Completion of 12th grade or equivalent",
      "UKVI IELTS 6.0 (no component below 5.5) for direct entry",
      "IELTS 4.5/5.0 accepted with foundation pathway",
      "Relevant academic background preferred",
    ],
    careerOutcomes: [
      "Startup Founder",
      "Business Development Manager",
      "Innovation Consultant",
      "Small Business Owner",
      "Venture Analyst",
      "Social Entrepreneur",
    ],
  },
  {
    id: 7,
    slug: "ba-business-studies-foundation",
    title: "BA (Hons) Business Studies with Foundation",
    subtitle: "4-Year Degree with Integrated Foundation",
    university: "UK Partner University",
    location: "London/Birmingham, UK",
    duration: "4 Years",
    mode: "Full-time",
    intake: "January, May, September 2024",
    tuitionFee: "Approx. £9,500 per year (Home)",
    tuitionFeeInternational: "£8,000 – £18,500 per year",
    rating: 4.4,
    reviews: 88,
    students: 1432,
    image: "https://images.unsplash.com/photo-1521791136064-7986c2920216?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
    category: "Business",
    description:
      "This programme includes a foundation year to prepare students for undergraduate study. It’s ideal for those who don’t meet direct entry requirements or are returning to education. After the foundation year, students progress to the full BA (Hons) Business Studies degree.",
    highlights: [
      "Includes foundation year",
      "No prior business background required",
      "Smooth transition to degree level",
      "Supportive learning environment",
      "Flexible entry requirements",
      "Pathway to honours degree",
    ],
    modules: [
      { name: "Academic Skills Development", duration: "Foundation Year" },
      { name: "Introduction to Business", duration: "Foundation Year" },
      { name: "Maths for Business", duration: "Foundation Year" },
      { name: "Communication Skills", duration: "Foundation Year" },
      { name: "Year 2–4: Full BA (Hons) Curriculum", duration: "Years 2-4" },
    ],
    requirements: [
      "Completion of 12th grade or equivalent",
      "UKVI IELTS 6.0 (no component below 5.5) for direct entry",
      "IELTS 4.5/5.0 accepted with foundation option",
      "Open to non-traditional learners",
    ],
    careerOutcomes: [
      "Business Analyst",
      "Marketing Coordinator",
      "Operations Assistant",
      "Graduate Trainee",
      "Administrative Manager",
      "Further postgraduate study",
    ],
  },
  {
    id: 8,
    slug: "bsc-accounting-finance",
    title: "BSc Accounting and Finance",
    subtitle: "Undergraduate Degree in Accounting & Finance",
    university: "UK Partner University",
    location: "London/Birmingham, UK",
    duration: "3 Years",
    mode: "Full-time",
    intake: "January, May, September 2024",
    tuitionFee: "Approx. £9,500 per year (Home)",
    tuitionFeeInternational: "£8,000 – £18,500 per year",
    rating: 4.7,
    reviews: 112,
    students: 1890,
    image: "/accounting.jpg",
    category: "Business",
    description:
      "This degree provides a solid foundation in accounting principles and financial management. It prepares students for careers in auditing, taxation, corporate finance, and financial analysis, with opportunities for professional accreditation.",
    highlights: [
      "ACCA/CIMA exemptions available",
      "Practical financial software training",
      "Industry guest lectures",
      "Strong employability focus",
      "Internship opportunities",
      "Globally recognised qualification",
    ],
    modules: [
      { name: "Financial Accounting", duration: "Year 1" },
      { name: "Management Accounting", duration: "Year 1" },
      { name: "Business Law", duration: "Year 1" },
      { name: "Corporate Finance", duration: "Year 2" },
      { name: "Taxation Principles", duration: "Year 2" },
      { name: "Audit & Assurance", duration: "Year 2" },
      { name: "Strategic Financial Management", duration: "Year 3" },
      { name: "Advanced Audit", duration: "Year 3" },
      { name: "Financial Reporting Standards", duration: "Year 3" },
    ],
    requirements: [
      "Completion of 12th grade or equivalent",
      "UKVI IELTS 6.0 (no component below 5.5)",
      "IELTS 4.5/5.0 accepted with foundation pathway",
    ],
    careerOutcomes: [
      "Chartered Accountant",
      "Financial Analyst",
      "Audit Associate",
      "Tax Advisor",
      "Finance Officer",
      "Banking Professional",
    ],
  },
  {
    id: 9,
    slug: "bsc-marketing",
    title: "BSc Marketing",
    subtitle: "Undergraduate Degree in Marketing",
    university: "UK Partner University",
    location: "London/Birmingham, UK",
    duration: "3 Years",
    mode: "Full-time",
    intake: "January, May, September 2024",
    tuitionFee: "Approx. £9,500 per year (Home)",
    tuitionFeeInternational: "£8,000 – £18,500 per year",
    rating: 4.6,
    reviews: 99,
    students: 1520,
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
    category: "Business",
    description:
      "This BSc in Marketing covers digital marketing, consumer behaviour, branding, and campaign management. Students gain hands-on experience through live projects and develop skills in analytics, social media, and strategic planning.",
    highlights: [
      "Digital marketing focus",
      "Live client projects",
      "Google & Meta certification prep",
      "Analytics and CRM tools training",
      "Internship placements",
      "Creative and strategic balance",
    ],
    modules: [
      { name: "Principles of Marketing", duration: "Year 1" },
      { name: "Consumer Behaviour", duration: "Year 1" },
      { name: "Digital Marketing Fundamentals", duration: "Year 1" },
      { name: "Brand Management", duration: "Year 2" },
      { name: "Marketing Analytics", duration: "Year 2" },
      { name: "Social Media Strategy", duration: "Year 2" },
      { name: "Integrated Marketing Communications", duration: "Year 3" },
      { name: "Global Marketing", duration: "Year 3" },
      { name: "Capstone Marketing Project", duration: "Year 3" },
    ],
    requirements: [
      "Completion of 12th grade or equivalent",
      "UKVI IELTS 6.0 (no component below 5.5)",
      "IELTS 4.5/5.0 accepted with foundation option",
    ],
    careerOutcomes: [
      "Digital Marketing Executive",
      "Brand Manager",
      "SEO/SEM Specialist",
      "Content Strategist",
      "Marketing Analyst",
      "Campaign Manager",
    ],
  },
  {
    id: 10,
    slug: "ba-business-human-resource-management",
    title: "BA (Hons) Business Human Resource Management",
    subtitle: "Undergraduate Degree in HR Management",
    university: "UK Partner University",
    location: "London/Birmingham, UK",
    duration: "3 Years",
    mode: "Full-time",
    intake: "January, May, September 2024",
    tuitionFee: "Approx. £9,500 per year (Home)",
    tuitionFeeInternational: "£8,000 – £18,500 per year",
    rating: 4.5,
    reviews: 91,
    students: 1345,
    image: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
    category: "Business",
    description:
      "This programme focuses on HR strategy, employment law, talent management, and organisational development. It prepares students for roles in HR departments across public, private, and non-profit sectors.",
    highlights: [
      "CIPD-aligned curriculum",
      "Employment law training",
      "Talent acquisition & development",
      "Workplace diversity & inclusion",
      "HR software skills",
      "Professional networking",
    ],
    modules: [
      { name: "Introduction to HRM", duration: "Year 1" },
      { name: "Organisational Behaviour", duration: "Year 1" },
      { name: "Employment Law", duration: "Year 1" },
      { name: "Talent Management", duration: "Year 2" },
      { name: "Performance Management", duration: "Year 2" },
      { name: "HR Analytics", duration: "Year 2" },
      { name: "Strategic HRM", duration: "Year 3" },
      { name: "Change Management", duration: "Year 3" },
      { name: "Global HR Practices", duration: "Year 3" },
    ],
    requirements: [
      "Completion of 12th grade or equivalent",
      "UKVI IELTS 6.0 (no component below 5.5)",
      "IELTS 4.5/5.0 accepted with foundation pathway",
    ],
    careerOutcomes: [
      "HR Assistant",
      "Recruitment Consultant",
      "Training Coordinator",
      "HR Business Partner",
      "Payroll Administrator",
      "People & Culture Manager",
    ],
  },
  {
    id: 11,
    slug: "level-5-diploma-education-training",
    title: "Level 5 Diploma in Education and Training",
    subtitle: "Diploma for Aspiring Teachers & Trainers",
    university: "UK Awarding Body",
    location: "London/Birmingham/Luton/Leeds, UK",
    duration: "1 Year",
    mode: "Full-time / Part-time",
    intake: "January, May, September 2024",
    tuitionFee: "£6,000",
    rating: 4.7,
    reviews: 67,
    students: 890,
    image: "educationTraining.jpg",
    category: "Education",
    description:
      "This Level 5 Diploma is designed for those seeking to become teachers or trainers in the Further Education and vocational sectors. It qualifies you to teach in colleges, training providers, and workplace settings.",
    highlights: [
      "Qualifies you to teach",
      "Ofqual-regulated qualification",
      "Practical teaching experience",
      "Flexible study modes",
      "Nationwide campuses",
      "Career progression in education",
    ],
    modules: [
      { name: "Teaching, Learning and Assessment", duration: "Core" },
      { name: "Curriculum Development", duration: "Core" },
      { name: "Inclusive Practice", duration: "Core" },
      { name: "Assessment Processes", duration: "Core" },
      { name: "Professional Development", duration: "Core" },
    ],
    requirements: [
      "Completion of 12th grade or equivalent",
      "Proof of ID and address",
      "Current CV",
      "Work reference",
      "UKVI IELTS 6.0 (no component below 5.5)",
      "IELTS 4.5/5.0 accepted with foundation",
    ],
    careerOutcomes: [
      "Further Education Teacher",
      "Corporate Trainer",
      "Vocational Instructor",
      "Learning and Development Officer",
      "Private Tutor",
      "Progress to PGCE",
    ],
  },
  {
    id: 12,
    slug: "hnc-hnd-business",
    title: "HNC and HND in Business",
    subtitle: "Higher National Certificate/Diploma in Business",
    university: "UK Awarding Body",
    location: "London/Birmingham/Luton/Leeds, UK",
    duration: "2 Years",
    mode: "Full-time",
    intake: "January, May, September 2024",
    tuitionFee: "£6,000 per year",
    rating: 4.4,
    reviews: 73,
    students: 1205,
    image: "https://images.unsplash.com/photo-1526948128573-703ee1aeb6fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
    category: "Business",
    description:
      "The HNC/HND in Business offers a practical and career-focused qualification. It covers core business functions and allows progression to the final year of a bachelor's degree or direct entry into employment.",
    highlights: [
      "Fast-track to degree or job",
      "Practical and applied learning",
      "BTEC or Pearson accredited",
      "Progression to Year 3 of BSc",
      "Employer-recognised qualification",
      "Flexible entry criteria",
    ],
    modules: [
      { name: "Business Environment", duration: "Year 1" },
      { name: "Marketing Processes", duration: "Year 1" },
      { name: "Human Resource Management", duration: "Year 1" },
      { name: "Business Accounting", duration: "Year 1" },
      { name: "Innovation & Entrepreneurship", duration: "Year 2" },
      { name: "Business Strategy", duration: "Year 2" },
      { name: "Project Management", duration: "Year 2" },
    ],
    requirements: [
      "Completion of 12th grade or equivalent",
      "Proof of ID and address",
      "Current CV",
      "Work reference",
      "UKVI IELTS 6.0 (no component below 5.5)",
    ],
    careerOutcomes: [
      "Junior Manager",
      "Administrative Supervisor",
      "Business Executive",
      "Progress to BSc Final Year",
      "Entrepreneur",
      "Customer Success Manager",
    ],
  },
];