export interface Course {
  id: number;
  slug: string;
  title: string;
  subtitle: string;
  university?: string;
  location: string;
  duration: string;
  mode: string;
  intake?: string;
  tuitionFee: string;
  tuitionFeeInternational?: string;
  rating: number;
  reviews: number;
  students: number;
  image: string;
  description: string;
  highlights: string[];
  modules: {
    name: string;
    credits?: number;
    duration?: string;
  }[];
  requirements: string[];
  careerOutcomes?: string[];
  category: string;
}

export const courses: Course[] = [
  {
    id: 1,
    slug: "skills-for-workplace",
    title: "Skills for Workplace",
    subtitle: "Certificate of Higher Education in Business",
    university: "University of Wales Trinity and Saint David",
    location: "Carmarthen, Wales",
    duration: "1 Year Full-time",
    mode: "Full-time",
    // intake: "September ",
    tuitionFee: "£9,535 per year",
    rating: 4.6,
    reviews: 89,
    students: 1324,
    image:
      "https://images.unsplash.com/photo-1573164574572-cb89e39749b4?fm=jpg&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YnVzaW5lc3MlMjB0cmFpbmluZ3xlbnwwfHwwfHx8MA%3D%3D&ixlib=rb-4.1.0&q=60&w=3000",
    category: "Business",
    description:
      "This course provides a broad overview of business, covering areas such as finance, human resources, marketing, and management. It emphasizes problem-solving, decision-making, leadership, and communication skills, preparing you to work effectively in teams or independently. The programme combines practical work experience with academic learning, helping you apply knowledge in real-world settings and enhancing employability. You’ll also gain insights into business culture, enterprise, entrepreneurship, and digital skills. As a CertHE, it serves as a strong foundation for further study or a career in business, equipping you with transferable skills for a variety of roles.",
    highlights: [
      "Practical work experience integrated",
      "Develops leadership & communication",
      "Pathway to full bachelor’s degree",
      "Focus on digital and employability skills",
      "Ideal for career changers or returners",
      "Support for international & mature students",
    ],
    modules: [
      { name: "Academic Skills", credits: 20 },
      { name: "Effective Teamworking and Communication", credits: 20 },
      { name: "Digital Skills", credits: 20 },
      { name: "Problem Solving and Decision Making", credits: 20 },
      { name: "Employability and Career Development", credits: 20 },
      { name: "Enterprise and Entrepreneurship", credits: 20 },
    ],
    requirements: [
      "Open to A-Levels, IB, Foundation programmes",
      "IELTS 6.0 (minimum 5.5 per component)",
      "Suitable for career returners or new learners",
      "Contextual admissions available",
      "Student visa required for international students",
      "US Federal Aid: in-person study only",
    ],
    careerOutcomes: [
      "Marketing and Sales",
      "Financial Services",
      "Public, private or third sector management",
      "Business Consultancy",
      "Postgraduate study/research",
    ],
  },
  {
    id: 2,
    slug: "fda-business-management",
    title: "FDA Business Management",
    subtitle: "Foundation Degree in Business Management",
    university: "New College Durham",
    location: "Durham, UK",
    duration: "2 Years Full-time",
    mode: "Full-time",
    tuitionFee: "£9,000 per year",
    rating: 4.5,
    reviews: 76,
    students: 942,
    image: "/business-management.jpg",
    category: "Business",
    description:
      "This programme is regularly updated to keep pace with the evolving business and management landscape, helping you take the first step on the management career ladder. Our lecturers bring real-world industry experience and a wide network of professional contacts to enrich your learning and strengthen your commercial awareness.",
    highlights: [
      "Industry-experienced lecturers",
      "Strong employer links",
      "Hands-on learning approach",
      "Pathway to full bachelor's degree",
      "Focus on leadership and enterprise",
      "Work-related learning modules",
    ],
    modules: [
      { name: "Personal Professional Development 1" },
      { name: "Innovation and Enterprise" },
      { name: "Human Resource Management" },
      { name: "Business Environment" },
      { name: "Principles of Marketing" },
      { name: "Leadership and Management" },
      { name: "Business Event Management" },
      { name: "Personal Professional Development 2" },
      { name: "Work Related Learning" },
      { name: "Entrepreneurship" },
      { name: "Business Finance" },
      { name: "Logistics and Supply Chain Management" },
      { name: "Developing Collaborative Relationships" },
      { name: "Principles of International Business" },
    ],
    requirements: [
      "Three GCSEs grade C/4 or above (including Maths and English)",
      "Minimum 32 UCAS Tariff Points",
      "Level 3 Business qualification or Access to HE",
      "IELTS 5.5 overall",
    ],
    careerOutcomes: [
      "Business Analyst",
      "Team Leader",
      "Operations Manager",
      "Entrepreneur",
      "HR Assistant",
      "Sales Executive",
    ],
  },
  {
    id: 3,
    slug: "mba-marketing",
    title: "Master of Business Administration (Marketing)",
    subtitle: "MBA with Specialisation in Marketing",
    university: "London/Birmingham",
    location: "London, UK",
    duration: "16-24 Months",
    mode: "Full-time / Part-time",
    intake: "January, May, September",
    tuitionFee: "£10,995 (Home/EU)",
    tuitionFeeInternational: "£17,500 (International)",
    rating: 4.8,
    reviews: 134,
    students: 2105,
    image:
      "https://images.unsplash.com/photo-1444653614773-995cb1ef9efa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
    category: "Business",
    description:
      "This MBA with a specialisation in Marketing is designed for professionals aiming to lead in dynamic marketing environments. The programme blends strategic management with advanced marketing concepts, equipping graduates with skills to drive brand growth and innovation in global markets.",
    highlights: [
      "Specialised in Marketing strategy",
      "Globally recognised MBA qualification",
      "Taught by industry experts",
      "Flexible start dates (Jan/May/Sep)",
      "Internationally recognised degree",
      "Part-time study options available",
    ],
    modules: [
      
    ],
    requirements: [
      "Minimum 2:2 UK Bachelor's degree or equivalent",
      "IELTS 6.5 (no component below 5.5)",
      "Applicants with IELTS 5.5–6.0 may take Pre-Sessional English",
      "Relevant work experience considered for non-standard applicants",
      "Pre-Master's available for qualification bridging",
    ],
    careerOutcomes: [
      "Marketing Manager",
      "Brand Director",
      "Digital Marketing Strategist",
      "Product Manager",
      "Market Research Analyst",
      "Advertising Executive",
    ],
  },
  {
    id: 4,
    slug: "mba-finance",
    title: "Master of Business Administration (Finance)",
    subtitle: "MBA with Specialisation in Finance",
    university: "London/Birmingham",
    location: "London, UK",
    duration: "16-24 Months",
    mode: "Full-time / Part-time",
    intake: "January, May, September",
    tuitionFee: "£10,995 (Home/EU)",
    tuitionFeeInternational: "£17,500 (international)",
    rating: 4.8,
    reviews: 128,
    students: 1973,
    image:
      "https://images.unsplash.com/photo-1591696205602-2f950c417cb9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
    category: "Business",
    description:
      "This MBA in Finance is tailored for aspiring financial leaders. It covers advanced financial management, investment analysis, and corporate strategy, preparing graduates for senior roles in banking, investment, and corporate finance sectors.",
    highlights: [
      "Access to high-quality education",
      "A wide variety of courses to choose from",
      "Development of essential skills for success",
      "Opportunities to join a diverse student community",
      "Ability to work part-time while studying",
      "Work placements to gain practical experience",
      "Internationally recognised degrees",
      "Improved English language proficiency",
    ],
    modules: [],
    requirements: [
      "Minimum 2:2 UK Bachelor's degree or equivalent",
      "IELTS 6.5 (no component below 5.5)",
      "Applicants with IELTS 5.5–6.0 may take Pre-Sessional English",
      "Pre-Master's available for qualification bridging",
    ],
    careerOutcomes: [
      "Financial Analyst",
      "Investment Banker",
      "Corporate Finance Manager",
      "Risk Consultant",
      "Portfolio Manager",
      "Chief Financial Officer (CFO)",
    ],
  },
  {
    id: 5,
    slug: "mba-general",
    title: "Master of Business Administration (MBA)",
    subtitle: "General MBA - Leadership & Management",
    university: "London/Birmingham",
    location: "London, UK",
    duration: "16-24 Months",
    mode: "Full-time / Part-time",
    intake: "January, May, September ",
    tuitionFee: "£10,995 (Home/EU)",
    tuitionFeeInternational: "£17,500 (International)",
    rating: 4.9,
    reviews: 203,
    students: 3560,
    image:
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
    category: "Business",
    description:
      "Our general MBA programme is designed to develop versatile business leaders. It covers core areas such as leadership, strategy, finance, marketing, and operations, providing a holistic understanding of modern business challenges.",
    highlights: [
      "Access to high-quality education",
      "Wide range of courses to choose from",
      "Development of essential skills for success",
      "Opportunities to join a vibrant student community",
      "Ability to work part-time while studying",
      "Work placements to gain practical experience",
      "Internationally recognised degrees",
      "Improved English language proficiency",
    ],
    modules: [],
    requirements: [
      "A minimum of a 2:2 (second-class) honours degree from a UK university or an equivalent qualification",
      "IELTS 6.5 or above, with no individual component below 5.5, or an equivalent English qualification",
      "Applicants with an IELTS score of 5.5–6.0 may be eligible to take a Pre-Sessional English course before starting the programme",
      "Applicants without the required academic qualifications may still be considered if they have significant experience in a business organisation and/or hold a relevant professional qualification.",
      "If you are unsure whether you meet the entry criteria, please contact us for guidance.",
      "Alternatively, you may be eligible to enrol in one of our Pre-Master’s programmes. These are designed to help students bridge any gaps in their qualifications. Successful completion of a Pre-Master’s programme will make you eligible to progress onto a Master’s degree.",
    ],

    careerOutcomes: [
      "General Manager",
      "Operations Director",
      "Business Consultant",
      "Entrepreneur",
      "Project Manager",
      "Senior Executive",
    ],
  },
  {
    id: 6,
    slug: "bsc-business-entrepreneurship",
    title: "BSc Business Management and Entrepreneurship",
    subtitle: "Undergraduate Degree in Business & Innovation",
    university: "London/Birmingham",
    location: "London/Birmingham, UK",
    duration: "3 Years",
    mode: "Full-time",
    intake: "January, May, September ",
    tuitionFee: "Approx. £9,500 per year (Home)",
    tuitionFeeInternational: "£8,000 – £18,500 per year (International)",
    rating: 4.5,
    reviews: 95,
    students: 1678,
    image:
      "https://images.unsplash.com/photo-1522071820081-009f0129c71c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
    category: "Business",
    description:
      "This degree combines core business principles with a strong focus on innovation and entrepreneurship. You’ll learn how to launch and manage startups, develop business plans, and think creatively about solving real-world problems.",
    highlights: [
      "Access to high-quality education",
      "Wide variety of courses",
      "Development of essential skills for success",
      "Opportunities to join a diverse student community",
      "Ability to work part-time while studying",
      "Work placements to gain practical experience",
      "Internationally recognised degrees",
      "Improved English language proficiency",
    ],
    modules: [],
    requirements: [
      "Successful Completion Of 12th Class Or Equivalent Qualification From Relevant Academic Background",
      "Students with a UKVI IELTS score of 4.5 or 5.0 may apply to an undergraduate programme with a foundation course at our partner universities.",
      "UKVI IELTS 6.0 overall, with no individual component below 5.5, is required for direct entry.",
    ],
    careerOutcomes: [
      "Startup Founder",
      "Business Development Manager",
      "Innovation Consultant",
      "Small Business Owner",
      "Venture Analyst",
      "Social Entrepreneur",
    ],
  },
  {
    id: 7,
    slug: "ba-business-studies-foundation",
    title: "BA (Hons) Business Studies with Foundation",
    subtitle: "3-Year Degree with Integrated Foundation",
    university: "London/Birmingham",
    location: "London/Birmingham, UK",
    duration: "3 Years",
    mode: "Full-time",
    intake: "January, May, September ",
    tuitionFee: "Approx. £9,500 per year (Home)",
    tuitionFeeInternational: "£8,000 – £18,500 per year (International)",
    rating: 4.4,
    reviews: 88,
    students: 1432,
    image:
      "https://images.unsplash.com/photo-1521791136064-7986c2920216?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
    category: "Business",
    description:
      "This programme includes a foundation year to prepare students for undergraduate study. It’s ideal for those who don’t meet direct entry requirements or are returning to education. After the foundation year, students progress to the full BA (Hons) Business Studies degree.",
    highlights: [
      "Access to high-quality education",
      "A wide selection of courses",
      "Development of essential skills for career success",
      "Opportunities to join a vibrant student community",
      "Options for part-time work while studying",
      "Work placements to gain practical experience",
      "Internationally recognised degrees",
      "Enhanced English language skills",
    ],
    modules: [],
    requirements: [
      "Successful completion of 12th grade or an equivalent qualification in a relevant academic field",
      "Students with a UKVI IELTS score of 4.5 or 5.0 may apply for an undergraduate programme with a foundation course at our partner universities.",
      "Direct entry requires a UKVI IELTS score of 6.0 overall, with no individual section below 5.5.",
    ],
    careerOutcomes: [
      "Business Analyst",
      "Marketing Coordinator",
      "Operations Assistant",
      "Graduate Trainee",
      "Administrative Manager",
      "Further postgraduate study",
    ],
  },
  {
    id: 8,
    slug: "bsc-accounting-finance",
    title: "BSc Accounting and Finance",
    subtitle: "Undergraduate Degree in Accounting & Finance",
    university: "London/Birmingham",
    location: "London/Birmingham, UK",
    duration: "3 Years",
    mode: "Full-time",
    intake: "January, May, September ",
    tuitionFee: "Approx. £9,500 per year (Home)",
    tuitionFeeInternational: "£8,000 – £18,500 per year (International)",
    rating: 4.7,
    reviews: 112,
    students: 1890,
    image: "/accounting.jpg",
    category: "Business",
    description:
      "This degree provides a solid foundation in accounting principles and financial management. It prepares students for careers in auditing, taxation, corporate finance, and financial analysis, with opportunities for professional accreditation.",
    highlights: [
      "Access to high-quality education",
      "Wide variety of courses to choose from",
      "Development of essential skills for success",
      "Opportunities to join a diverse student community",
      "Ability to work part-time while studying",
      "Work placements to gain practical experience",
      "Internationally recognised degrees",
      "Enhanced English language skills",
    ],
    modules: [],
    requirements: [
      "Successful completion of 12th grade, or an equivalent qualification, in a relevant academic field",
      "Students with a UKVI IELTS score of 4.5 or 5.0 may apply for an undergraduate programme with a foundation course at our partner universities",
      "Direct entry requires a UKVI IELTS score of 6.0 overall, with no individual section below 5.5",
    ],
    careerOutcomes: [
      "Chartered Accountant",
      "Financial Analyst",
      "Audit Associate",
      "Tax Advisor",
      "Finance Officer",
      "Banking Professional",
    ],
  },
  {
    id: 9,
    slug: "bsc-marketing",
    title: "BSc Marketing",
    subtitle: "Undergraduate Degree in Marketing",
    university: "London/Birmingham, UK",
    location: "London/Birmingham, UK",
    duration: "3 Years",
    mode: "Full-time",
    intake: "January, May, September ",
    tuitionFee: "Approx. £9,500 per year (Home)",
    tuitionFeeInternational: "£8,000 – £18,500 per year (International)",
    rating: 4.6,
    reviews: 99,
    students: 1520,
    image:
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
    category: "Business",
    description:
      "This BSc in Marketing covers digital marketing, consumer behaviour, branding, and campaign management. Students gain hands-on experience through live projects and develop skills in analytics, social media, and strategic planning.",
    highlights: [
      "Access to excellent education",
      "A wide variety of courses",
      "Development of essential skills for success",
      "Opportunities to engage with a large and diverse student community",
      "Options for part-time work while studying",
      "Work placements to gain practical experience",
      "Internationally recognised qualifications",
      "Improved English language skills",
      "Successful Completion Of 12th Class Or Equivalent Qualification From Relevant Academic Background",
    ],
    modules: [],
    requirements: [
      "Completion of 12th grade or equivalent",
      "UKVI IELTS 6.0 (no component below 5.5)",
      "IELTS 4.5/5.0 accepted with foundation option",
    ],
    careerOutcomes: [
      "Digital Marketing Executive",
      "Brand Manager",
      "SEO/SEM Specialist",
      "Content Strategist",
      "Marketing Analyst",
      "Campaign Manager",
    ],
  },
  {
    id: 10,
    slug: "ba-business-human-resource-management",
    title: "BA (Hons) Business Human Resource Management",
    subtitle: "Undergraduate Degree in HR Management",
    university: "London/Birmingham",
    location: "London/Birmingham, UK",
    duration: "3 Years",
    mode: "Full-time",
    intake: "January, May, September ",
    tuitionFee: "Approx. £9,500 per year (Home)",
    tuitionFeeInternational: "£8,000 – £18,500 per year (International)",
    rating: 4.5,
    reviews: 91,
    students: 1345,
    image:
      "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
    category: "Business",
    description:
      "This programme focuses on HR strategy, employment law, talent management, and organisational development. It prepares students for roles in HR departments across public, private, and non-profit sectors.",
    highlights: [
      "Access to high-quality education",
      "A wide variety of courses",
      "Development of essential skills for success",
      "Opportunities to join a vibrant student community",
      "Ability to work part-time while studying",
      "Work placements to gain practical experience",
      "Internationally recognised degrees",
      "Improved English language skills",
    ],
    modules: [],
    requirements: [
      "Completion of 12th grade or equivalent",
      "UKVI IELTS 6.0 (no component below 5.5)",
      "IELTS 4.5/5.0 accepted with foundation pathway",
    ],
    careerOutcomes: [
      "HR Assistant",
      "Recruitment Consultant",
      "Training Coordinator",
      "HR Business Partner",
      "Payroll Administrator",
      "People & Culture Manager",
    ],
  },
  {
    id: 11,
    slug: "level-5-diploma-education-training",
    title: "Level 5 Diploma in Education and Training",
    subtitle: "Diploma for Aspiring Teachers & Trainers",
    university: "London/Birmingham/Luton/Leed",
    location: "London/Birmingham/Luton/Leeds, UK",
    duration: "1 Year",
    mode: "Full-time / Part-time",
    intake: "January, May, September ",
    tuitionFee: "£6,000",
    rating: 4.7,
    reviews: 67,
    students: 890,
    image: "educationTraining.jpg",
    category: "Education",
    description:
      "This Level 5 Diploma is designed for those seeking to become teachers or trainers in the Further Education and vocational sectors. It qualifies you to teach in colleges, training providers, and workplace settings.",
    highlights: [
      "Access to high-quality education",
      "A wide variety of courses",
      "Development of skills essential for success",
      "Opportunities to join a large and diverse student community",
      "Possibility to work part-time while studying",
      "Work placements to gain practical experience",
      "Internationally recognised degrees",
      "Enhanced English language proficiency",
    ],
    modules: [
    
    ],
    requirements: [
     "Successful Completion Of 12th Class Or Equivalent Qualification From Relevant Academic Background",
  "Proof of ID",
  "Proof of Address",
  "Current CV",
  "Work Reference",
  "If student has UKVI IELTS 5.0 or 4.5 score, they can apply to undergraduate programme with foundation at our partner universities",
  "UKVI IELTS 6.0 (no less than 5.5 in any individual section)",
    ],
    careerOutcomes: [
      "Further Education Teacher",
      "Corporate Trainer",
      "Vocational Instructor",
      "Learning and Development Officer",
      "Private Tutor",
      "Progress to PGCE",
    ],
  },
  {
    id: 12,
    slug: "hnc-hnd-business",
    title: "HNC and HND in Business",
    subtitle: "Higher National Certificate/Diploma in Business",
    university: "London/Birmingham/Luton/Leeds",
    location: "London/Birmingham/Luton/Leeds, UK",
    duration: "2 Years",
    mode: "Full-time",
    intake: "January, May, September ",
    tuitionFee: "£6,000 per year",
    rating: 4.4,
    reviews: 73,
    students: 1205,
    image:
      "https://images.unsplash.com/photo-1526948128573-703ee1aeb6fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
    category: "Business",
    description:
      "The HNC/HND in Business offers a practical and career-focused qualification. It covers core business functions and allows progression to the final year of a bachelor's degree or direct entry into employment.",
    highlights: [
        "Access to high-quality education",
  "A wide variety of courses",
  "Development of essential skills for career success",
  "Opportunities to engage with a large and diverse student community",
  "Options for part-time work while studying",
  "Work placements to gain practical experience",
  "Internationally recognised degrees",
  "Enhanced English language proficiency",
    ],
    modules: [
     
    ],
    requirements: [
     "Successful Completion Of 12th Class Or Equivalent Qualification From Relevant Academic Background",
  "Proof of ID",
  "Proof of Address",
  "Current CV",
  "Work Reference",
  "If student has UKVI IELTS 5.0 or 4.5 score, they can apply to undergraduate programme with foundation at our partner universities",
  "UKVI IELTS 6.0 (no less than 5.5 in any individual section)",
    ],
    careerOutcomes: [
      "Junior Manager",
      "Administrative Supervisor",
      "Business Executive",
      "Progress to BSc Final Year",
      "Entrepreneur",
      "Customer Success Manager",
    ],
  },
{
  id: 13,
  slug: "hnc-hnd-healthcare-practice",
  title: "HNC and HND in Healthcare Practice",
  subtitle: "Higher National Certificate/Diploma in Healthcare Practice",
  university: "London/Birmingham/Luton/Leeds",
  location: "London/Birmingham/Luton/Leeds, UK",
  duration: "2 Years",
  mode: "Full-time",
  intake: "January, May, September",
  tuitionFee: "£6,000 per year",
  rating: 4.4,
  reviews: 73,
  students: 1205,
  image:
    "https://images.unsplash.com/photo-1526948128573-703ee1aeb6fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
  category: "Healthcare",
  description:
    "The HNC/HND in Healthcare Practice provides a career-focused qualification, offering students the opportunity to gain practical skills and theoretical knowledge essential for a successful career in the healthcare sector. Graduates can progress to the final year of a bachelor's degree or move directly into employment.",
  highlights: [
    "Access to high-quality education",
    "A wide variety of courses",
    "Development of essential skills for career success",
    "Opportunities to engage with a large and diverse student community",
    "Options for part-time work while studying",
    "Work placements to gain practical experience",
    "Internationally recognised degrees",
    "Enhanced English language proficiency",
  ],
  modules: [],
  requirements: [
    "Successful Completion Of 12th Class Or Equivalent Qualification From Relevant Academic Background",
    "Proof of ID",
    "Proof of Address",
    "Current CV",
    "Work Reference",
    "If student has UKVI IELTS 5.0 or 4.5 score, they can apply to undergraduate programme with foundation at our partner universities",
    "UKVI IELTS 6.0 (no less than 5.5 in any individual section)",
  ],
  careerOutcomes: [
    "Healthcare Support Worker",
    "Senior Care Assistant",
    "Assistant Practitioner",
    "Progress to BSc Final Year",
    "Care Coordinator",
    "Community Support Worker",
  ],
},
{
  id: 14,
  slug: "ba-hons-business-management-sustainability",
  title: "BA (Hons) Business Management and Sustainability",
  subtitle: "Bachelor of Arts in Business Management and Sustainability",
  university: "London/Birmingham/Luton/Leeds",
  location: "London/Birmingham/Luton/Leeds, UK",
  duration: "3 Years / 4 Years",
  mode: "Full-time",
  intake: "January, September",
  tuitionFee: "Approximately £9,500 per year",
  rating: 4.5,
  reviews: 89,
  students: 1320,
  image:
    "https://images.unsplash.com/photo-1521790797524-b2497295b8a0?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
  category: "Business",
  description:
    "The BA (Hons) Business Management and Sustainability degree equips students with the knowledge and skills to lead and innovate in sustainable business practices. This programme blends core business management principles with a focus on environmental, social, and governance (ESG) strategies, preparing graduates for impactful roles in modern organisations.",
  highlights: [
    "Access to world-class education",
    "A diverse selection of courses",
    "Development of essential skills for success",
    "Opportunities to join a vibrant student community",
    "Ability to work part-time while studying",
    "Work placements to gain practical experience",
    "Internationally recognised degrees",
    "Improved English language skills",
  ],
  modules: [],
  requirements: [
    "Successful Completion Of 12th Class Or Equivalent Qualification From Relevant Academic Background",
    "Proof of ID",
    "Proof of Address",
    "Current CV",
    "Work Reference",
    "If student has UKVI IELTS 5.0 or 4.5 score, they can apply to undergraduate programme with foundation at our partner universities",
    "UKVI IELTS 6.0 (no less than 5.5 in any individual section)",
  ],
  careerOutcomes: [
    "Sustainability Consultant",
    "Business Development Manager",
    "Corporate Social Responsibility (CSR) Manager",
    "Project Manager",
    "Operations Manager",
    "Entrepreneur",
  ],
},
{
  id: 15,
  slug: "ba-hons-business-management-top-up",
  title: "BA (Hons) Business Management (Top Up)",
  subtitle: "Bachelor of Arts in Business Management (Top Up)",
  university: "London/Birmingham/Luton/Leeds",
  location: "London/Birmingham/Luton/Leeds, UK",
  duration: "3 Years",
  mode: "Full-time",
  intake: "January, September",
  tuitionFee: "Approximately £9,500 per year",
  rating: 4.5,
  reviews: 84,
  students: 1280,
  image:
    "https://images.unsplash.com/photo-1532012197267-da84d127e765?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
  category: "Business",
  description:
    "The BA (Hons) Business Management (Top Up) programme is designed for students who have completed a relevant diploma or foundation degree and wish to progress to a full bachelor's degree. The course develops strategic thinking, leadership, and management skills to prepare graduates for professional success in dynamic business environments.",
  highlights: [
    "Access to high-quality education",
    "A broad range of courses",
    "Development of skills essential for success",
    "Opportunities to connect with a large and diverse student community",
    "Options to work part-time while studying",
    "Work placements to gain practical experience",
    "Internationally recognised degrees",
    "Improved English language proficiency",
  ],
  modules: [],
  requirements: [
    "Successful Completion Of 12th Class Or Equivalent Qualification From Relevant Academic Background",
    "Proof of ID",
    "Proof of Address",
    "Current CV",
    "Work Reference",
    "If student has UKVI IELTS 5.0 or 4.5 score, they can apply to undergraduate programme with foundation at our partner universities",
    "UKVI IELTS 6.0 (no less than 5.5 in any individual section)",
  ],
  careerOutcomes: [
    "Business Development Manager",
    "Operations Manager",
    "Project Manager",
    "Marketing Executive",
    "Entrepreneur",
    "Management Consultant",
  ],
},
{
  id: 16,
  slug: "ba-hons-business-and-hospitality-management",
  title: "BA (Hons) Business and Hospitality Management",
  subtitle: "Bachelor of Arts in Business and Hospitality Management",
  university: "London/Birmingham",
  location: "London/Birmingham, UK",
  duration: "3 Years",
  mode: "Full-time",
  intake: "January, May, September",
  tuitionFee: "EU/Home: Approximately £9,500 per year | International: £8,000 to £18,500 per year",
  rating: 4.5,
  reviews: 91,
  students: 1100,
  image:
    "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
  category: "Business & Hospitality",
  description:
    "The BA (Hons) Business and Hospitality Management programme equips students with the essential business and customer service skills needed to excel in the hospitality industry. Combining academic knowledge with practical training, this course prepares graduates for leadership roles in hotels, tourism, and event management.",
  highlights: [
    "Access to world-class education",
    "A broad selection of courses",
    "Development of essential skills for future success",
    "Opportunities to join a diverse and vibrant student community",
    "Options for part-time work while studying",
    "Work placements to gain practical experience",
    "Internationally recognised degrees",
    "Enhanced English language proficiency",
  ],
  modules: [],
  requirements: [
    "Successful Completion Of 12th Class Or Equivalent Qualification From Relevant Academic Background",
    "Students with a UKVI IELTS score of 4.5 or 5.0 may apply for an undergraduate programme with a foundation course at our partner universities",
    "Direct entry requires a UKVI IELTS score of 6.0 overall, with no individual component below 5.5",
  ],
  careerOutcomes: [
    "Hotel Manager",
    "Event Coordinator",
    "Restaurant Manager",
    "Tourism Manager",
    "Business Development Executive",
    "Hospitality Consultant",
  ],
},
{
  id: 17,
  slug: "ba-hons-business-management",
  title: "BA (Hons) Business Management",
  subtitle: "Bachelor of Arts in Business Management",
  university: "London/Birmingham",
  location: "London/Birmingham, UK",
  duration: "3 Years",
  mode: "Full-time",
  intake: "January, May, September",
  tuitionFee: "EU/Home: Approximately £9,500 per year | International: £8,000 to £18,500 per year",
  rating: 4.5,
  reviews: 95,
  students: 1400,
  image:
    "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
  category: "Business",
  description:
    "The BA (Hons) Business Management degree offers comprehensive knowledge and practical skills in key business areas, preparing students for successful careers in management and leadership across a variety of industries.",
  highlights: [
    "Access to high-quality education",
    "Wide range of courses to choose from",
    "Development of essential skills for career success",
    "Opportunities to engage with a diverse student community",
    "Options for part-time work while studying",
    "Work placements to gain practical experience",
    "Internationally recognised degrees",
    "Enhanced English language skills",
  ],
  modules: [],
  requirements: [
    "Successful Completion Of 12th Class Or Equivalent Qualification From Relevant Academic Background",
    "Students with a UKVI IELTS score of 4.5 or 5.0 may be eligible to apply for an undergraduate programme with a foundation course at our partner universities",
    "Direct entry requires a UKVI IELTS score of 6.0 overall, with no individual section below 5.5",
  ],
  careerOutcomes: [
    "Business Analyst",
    "Operations Manager",
    "Marketing Executive",
    "Project Manager",
    "Entrepreneur",
    "Management Consultant",
  ],
},
{
  id: 18,
  slug: "bsc-hons-nursing-adult-and-child",
  title: "BSc (Hons) Nursing (Adult and Child)",
  subtitle: "Bachelor of Science in Nursing (Adult and Child)",
  university: "London/Birmingham",
  location: "London, UK",
  duration: "3 Years",
  mode: "Full-time",
  intake: "January, May, September",
  tuitionFee: "£9,500 (Home/EU)",
  tuitionFeeInternational: "£8,000 to £18,500 (International)",
  rating: 4.6, 
  reviews: 120, 
  students: 1100, 
  image:
    "/nurse.jpg",
  category: "Health & Nursing",
  description:
    "The BSc (Hons) Nursing (Adult and Child) degree equips students with theoretical knowledge and practical skills to provide professional nursing care to both adults and children across healthcare settings.",
  highlights: [
    "Access to high-quality education",
    "Broad selection of courses",
    "Development of essential skills for success",
    "Opportunities to join a vibrant student community",
    "Ability to work part-time while studying",
    "Work placements to gain practical experience",
    "Internationally recognised degrees",
    "Improved English language skills",
  ],
  modules: [
   
  ],
  requirements: [
    "Successful completion of 12th class or equivalent qualification from relevant academic background",
    "Students with a UKVI IELTS score of 4.5 or 5.0 may apply for an undergraduate programme with a foundation course at our partner universities",
    "Direct entry requires a UKVI IELTS score of 6.0 overall, with no individual section below 5.5",
  ],
  careerOutcomes: [
    "Registered Nurse (Adult Care)",
    "Paediatric Nurse",
    "Community Health Nurse",
    "Clinical Nurse Specialist",
    "Healthcare Advisor",
    "Nursing Educator",
  ],
}






];
